name: Run tests

on: [pull_request]

jobs:
  TestsAndOthers:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Chekout code
        uses: actions/checkout@v3

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run unit test
        run: npm run test:unit