name: Deploy with CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout code
      uses: actions/checkout@v3

    - name: Install node required
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Build dist
      run: npm run build

    - name: Deploy to GH Pages
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: deploy
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}