name: Deploy with CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout code
      uses: actions/checkout@v3

    - name: Install node required 
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Install dependencies
      run: npm ci

    - name: Build dist
      run: |
        npm run clean
        npm run dev
      
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
       github_token: ${{ secrets.PORTFOLIO_SECRET }}
       publish_dir: dist
      
      
